version: '3'
services:
  server:
    build: .
    ports:
      - 5000:5000
    environment:
      ROUND_COUNT: 4
      SECRET: 123
      DATABASE_URL: postgres://root:Root123@db:5432/Todo
      PORT: 5000
      REDIS_URL: redis://cache:6379/0
    depends_on:
      - db
      - redis
    restart:
      on-failure
    container_name: api
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Todo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Root123
    container_name: db
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart:
      always
    container_name: cache
volumes:
  db-data:
  redis-data:
