version: '3'
services:
  # server:
  #   build: .
  #   ports:
  #     - '5000:5000'
  #   container_name: server-container
  #   environment:
  #     ROUND_COUNT: 4
  #     SECRET: 123
  #     DATABASE_URL: mysql://root:Root123@db-container:3306/Todo
  #     PORT: 5000
  #     REDIS_HOST: localhost
  #     REDIS_PORT: 6739
  #   depends_on:
  #     - db
  #     - redis
  #   restart:
  #     on-failure
  db:
    image: postgres:alpine
    restart: always
    ports:
      - '3308:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Todo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Root123
    container_name: db-container

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    container_name: redis-container
    restart:
      always
volumes:
  db-data:
  redis-data:
