version: '3'
services:
  server:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      ROUND_COUNT: 4
      SECRET: 123
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
      PORT: 5000
      REDIS_URL: redis://cache:6379/0
      EMAIL_HOST: smtp.sendgrid.net
      EMAIL_USER: apikey
      EMAIL_PASS: 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
      EMAIL_FROM: beautifultask@yandex.ru
      EMAIL_PORT: 587
    depends_on:
      - db
      - redis
    restart: always
    container_name: api
  db:
    image: postgres:alpine
    ports:
      - 5433:5432
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    container_name: db
  redis:
    image: redis:alpine
    env_file:
      - .env
    volumes:
      - redis-data:/data
    restart:
      always
    container_name: cache
volumes:
  db-data:
  redis-data:
