version: '3'
services:
  server:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env.production
    depends_on:
      - db
      - redis
    restart: always
    container_name: api
  db:
    image: postgres:alpine
    ports:
      - 5433:5432
    restart: always
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    env_file:
      - .env.production
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    container_name: db
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    env_file:
      - .env.production
    volumes:
      - redis-data:/data
    restart:
      always
    container_name: cache
volumes:
  # db-data:
  redis-data:
